//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTemplateStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfTemplateStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WpfTemplateStudio.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Remover.
        /// </summary>
        public static string BackgroundRemoverPageTitle {
            get {
                return ResourceManager.GetString("BackgroundRemoverPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background removed.
        /// </summary>
        public static string BackgroundRemoverViewModel_RemoveBackgroundAsync_BackgroundRemoved {
            get {
                return ResourceManager.GetString("BackgroundRemoverViewModel_RemoveBackgroundAsync_BackgroundRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not found.
        /// </summary>
        public static string BackgroundRemoverViewModel_RemoveBackgroundAsync_ImageNotFound {
            get {
                return ResourceManager.GetString("BackgroundRemoverViewModel_RemoveBackgroundAsync_ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing background....
        /// </summary>
        public static string BackgroundRemoverViewModel_RemoveBackgroundAsync_RemovingBackground {
            get {
                return ResourceManager.GetString("BackgroundRemoverViewModel_RemoveBackgroundAsync_RemovingBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files (*.jpg, *.jpeg, *.png)|*.jpg;*.jpeg;*.png.
        /// </summary>
        public static string BackgroundRemoverViewModel_SelectImageAsync_ImageFilter {
            get {
                return ResourceManager.GetString("BackgroundRemoverViewModel_SelectImageAsync_ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image selected.
        /// </summary>
        public static string BackgroundRemoverViewModel_SelectImageAsync_ImageSelected {
            get {
                return ResourceManager.GetString("BackgroundRemoverViewModel_SelectImageAsync_ImageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting image....
        /// </summary>
        public static string BackgroundRemoverViewModel_SelectImageAsync_SelectingImage {
            get {
                return ResourceManager.GetString("BackgroundRemoverViewModel_SelectImageAsync_SelectingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        public static string BlankPageTitle {
            get {
                return ResourceManager.GetString("BlankPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentGrid.
        /// </summary>
        public static string ContentGridPageTitle {
            get {
                return ResourceManager.GetString("ContentGridPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGrid.
        /// </summary>
        public static string DataGridPageTitle {
            get {
                return ResourceManager.GetString("DataGridPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string ListDetailsListDescription {
            get {
                return ResourceManager.GetString("ListDetailsListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListDetails.
        /// </summary>
        public static string ListDetailsPageTitle {
            get {
                return ResourceManager.GetString("ListDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file to sign.
        /// </summary>
        public static string RsaDigitalSigningPage_AddFileToSign {
            get {
                return ResourceManager.GetString("RsaDigitalSigningPage.AddFileToSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file to verify.
        /// </summary>
        public static string RsaDigitalSigningPage_AddFileToVerify {
            get {
                return ResourceManager.GetString("RsaDigitalSigningPage.AddFileToVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital signature.
        /// </summary>
        public static string RsaDigitalSigningPage_DigitalSignature {
            get {
                return ResourceManager.GetString("RsaDigitalSigningPage.DigitalSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate key.
        /// </summary>
        public static string RsaDigitalSigningPage_GenerateKey {
            get {
                return ResourceManager.GetString("RsaDigitalSigningPage.GenerateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get digital signature.
        /// </summary>
        public static string RsaDigitalSigningPage_GetDigitalSignature {
            get {
                return ResourceManager.GetString("RsaDigitalSigningPage.GetDigitalSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key.
        /// </summary>
        public static string RsaDigitalSigningPage_PrivateKey {
            get {
                return ResourceManager.GetString("RsaDigitalSigningPage.PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key.
        /// </summary>
        public static string RsaDigitalSigningPage_PublicKey {
            get {
                return ResourceManager.GetString("RsaDigitalSigningPage.PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify data.
        /// </summary>
        public static string RsaDigitalSigningPage_VerifyData {
            get {
                return ResourceManager.GetString("RsaDigitalSigningPage.VerifyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSA Digital Signing.
        /// </summary>
        public static string RsaDigitalSigningPageTitle {
            get {
                return ResourceManager.GetString("RsaDigitalSigningPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings page placeholder text.  Your app description goes here..
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this application.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackgroundRemover.
        /// </summary>
        public static string ShellBackgroundRemoverPage {
            get {
                return ResourceManager.GetString("ShellBackgroundRemoverPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        public static string ShellBlankPage {
            get {
                return ResourceManager.GetString("ShellBlankPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContentGrid.
        /// </summary>
        public static string ShellContentGridPage {
            get {
                return ResourceManager.GetString("ShellContentGridPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataGrid.
        /// </summary>
        public static string ShellDataGridPage {
            get {
                return ResourceManager.GetString("ShellDataGridPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or close navigation.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListDetails.
        /// </summary>
        public static string ShellListDetailsPage {
            get {
                return ResourceManager.GetString("ShellListDetailsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RsaDigitalSigning.
        /// </summary>
        public static string ShellRsaDigitalSigningPage {
            get {
                return ResourceManager.GetString("ShellRsaDigitalSigningPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView.
        /// </summary>
        public static string ShellWebViewPage {
            get {
                return ResourceManager.GetString("ShellWebViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back (Alt + Left).
        /// </summary>
        public static string WebViewPageBackButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageBackButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page failed to load. Check connection and retry..
        /// </summary>
        public static string WebViewPageFaildedMessage {
            get {
                return ResourceManager.GetString("WebViewPageFaildedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward (Alt + Right).
        /// </summary>
        public static string WebViewPageForwardButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageForwardButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string WebViewPageLoadingText {
            get {
                return ResourceManager.GetString("WebViewPageLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in browser (Ctrl + T).
        /// </summary>
        public static string WebViewPageOpenInBrowserButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageOpenInBrowserButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh (F5).
        /// </summary>
        public static string WebViewPageRefreshButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageRefreshButtonTooltip", resourceCulture);
            }
        }
    }
}
